### ISSUE TITLE
Table Access Errors: slack_access_logs and slack_search

### ISSUE THREAD

**Issue by petewilcock** [turbot/steampipe-plugin-slack#3]
Scopes configured as docs: 

![image](https://user-images.githubusercontent.com/6526265/105879356-f95c4000-5ff9-11eb-987c-e1ddbf21f645.png)

`slack_access_log` throws: `Error: pq: rpc error: code = Unknown desc = paid_only` - is this table not accessible on a free plan?

`slack_search` throws: `Error: pq: rpc error: code = Internal desc = 'List' call requires an '=' qual for column: query`

Would be happy to learn if I'm being stupid :)

**Comment by e-gineer** [comment]
`slack_search` needs the `query` field to be specified in the `where` clause for all queries - otherwise it doesn't know what to search for. Please try something like `select * from slack_search where query = 'steampipe'`. I've updated the docs for the next version to better highlight this.

It does appear that `slack_access_log` is [a paid feature](https://slack.com/help/articles/360002084807-View-Access-Logs-for-your-workspace). I've updated the docs to explain this as well.

Hope that helps, thanks for the report!
